name: backend-base-devops
services:
  backend:
    image: localhost:8082/backend-base-devops:latest
    ports:
      - "3002:3001"
    env_file:
      - .local-env
  gitlab:
    profiles: ['not-start']
    image: gitlab/gitlab-ee:16.10.1-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.carlosmarind.cl'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.carlosmarind.cl'
    ports:
      - '8085:80'
      - '8086:443'
      - '22:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    restart: always
    ports:
      - "8087:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8088:8081"
      - "8089:8082"
      - "8090:8083"
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db_sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "8091:9000"
  db_sonar:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins_home:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: